const ModelActionTypes = {
    UPDATE_SONG_LIST: 'UPDATE_SONG_LIST',
    UPDATE_ARTIST_LIST: 'UPDATE_ARTIST_LIST',
    UPDATE_CHART_LIST: 'UPDATE_CHART_LIST',
    UPDATE_CURRENT_SONG: 'UPDATE_CURRENT_SONG',
    UPDATE_CURRENT_ARTIST: 'UPDATE_CURRENT_ARTIST',
    UPDATE_CURRENT_CHART: 'UPDATE_CURRENT_CHART'
};

export default ModelActionTypes;
